# Functions related to calculating K-mer motif enrichment from peak data.

#' Calculate Average K-mer Counts from Background Sets
#'
#' @description This function calculates the average K-mer counts over multiple
#'   iterations of background sequence generation. For each iteration, it generates
#'   a new set of background sequences using `generateBkgSet`, counts K-mers
#'   using `countKmers`, and then averages these counts across all iterations.
#'
#' @param original_peak_gr A GRanges object representing the initial peaks from
#'   which background regions are derived.
#' @param K Integer, the length of K-mers to count.
#' @param type Character string, "DNA" or "RNA" (case-insensitive), defining the
#'   alphabet for K-mer generation. Passed to `countKmers` and used to
#'   generate the K-mer universe. Default: "DNA".
#' @param genome_obj A BSgenome object for sequence retrieval by `generateBkgSet`.
#' @param bkg_min_dist Integer, the minimum absolute distance (in base pairs) for
#'   shifting peaks. Passed to `generateBkgSet`. Default: 500.
#' @param bkg_iter Integer, the number of background iterations to perform.
#'   Default: 100.
#' @param bkg_max_dist Integer, the maximum absolute distance (in base pairs)
#'   for shifting peaks. Passed to `generateBkgSet`. Default: 1000.
#' @param internal_min_length_for_bkg_seqs Integer, minimum length for sequences
#'   generated by `generateBkgSet` (passed as `K` to `generateBkgSet` which
#'   passes it as `min_length` to `getSequence`). Default is `K` from this function.
#' @param scramble_bkg Logical, if TRUE (default), scrambles background sequences.
#'   Set to FALSE for faster execution when scrambling is not needed.
#'
#' @return A list with four elements:
#'   \describe{
#'     \item{MOTIF}{Character vector of all possible K-mers.}
#'     \item{bkg_total_count}{Integer vector, total occurrences of
#'       each K-mer pooled across all background iterations (ANR).}
#'     \item{bkg_presence_count}{Integer vector, number of background
#'       sequences containing each K-mer at least once, pooled
#'       across all iterations (ZOOPS).}
#'     \item{bkg_total_seqs}{Integer, total number of background
#'       sequences generated across all iterations.}
#'   }
#'
#' @importFrom Biostrings DNAStringSet
#' @importFrom S4Vectors elementNROWS
#' @importFrom utils txtProgressBar setTxtProgressBar
#' @importFrom methods is
#'
#' @keywords internal # Helper for the main motifEnrichment function
countKmersBkg <- function(original_peak_gr, K, type = "DNA", genome_obj,
                          bkg_min_dist = 500, bkg_iter = 100, bkg_max_dist = 1000,
                          internal_min_length_for_bkg_seqs = K, scramble_bkg = TRUE,
                          chunk_size = NULL, extension = c(0L, 0L)) {
  # --- Input Validation ---
  if (!methods::is(original_peak_gr, "GRanges") || length(original_peak_gr) == 0) {
    stop("'original_peak_gr' must be a non-empty GRanges object.")
  }
  if (!is.numeric(bkg_iter) || length(bkg_iter) != 1 || bkg_iter <= 0 || bkg_iter %% 1 != 0) {
    stop("'bkg_iter' must be a single positive integer.")
  }
  if (!is.numeric(internal_min_length_for_bkg_seqs) || length(internal_min_length_for_bkg_seqs) != 1 ||
    internal_min_length_for_bkg_seqs < 1 || internal_min_length_for_bkg_seqs %% 1 != 0) {
    stop("'internal_min_length_for_bkg_seqs' must be a single positive integer.")
  }
  if (internal_min_length_for_bkg_seqs < K) {
    warning(
      "'internal_min_length_for_bkg_seqs' (", internal_min_length_for_bkg_seqs,
      ") is less than K (", K, "). Background sequences might be too short for K-mer counting."
    )
  }

  message("Note: During background generation, any regions shorter than K=", K, " will be removed.")

  # --- Auto-calculate chunk_size for memory safety ---
  if (is.null(chunk_size)) {
    num_peaks <- length(original_peak_gr)
    num_kmers <- 4^K
    # Target ~1 GB for the oligonucleotideFrequency matrix
    # Matrix size per iteration = num_peaks * num_kmers * 4 bytes (integer)
    bytes_per_iter <- as.numeric(num_peaks) * num_kmers * 4
    if (bytes_per_iter > 0) {
      chunk_size <- max(1L, as.integer(floor(1e9 / bytes_per_iter)))
    } else {
      chunk_size <- bkg_iter
    }
    chunk_size <- min(chunk_size, bkg_iter)
  }

  # --- Template k-mers ---
  template_kmers_df <- suppressMessages(countKmers(sequences = Biostrings::DNAStringSet(), K = K, type = type))
  all_kmers_vector <- template_kmers_df$MOTIF

  if (length(all_kmers_vector) == 0 && K > 0) {
    stop("Could not generate the K-mer universe template. Check K and type parameters for countKmers.")
  }

  # --- Accumulator matrices ---
  counts_accumulator_matrix <- matrix(0L,
      nrow = length(all_kmers_vector),
      ncol = bkg_iter,
      dimnames = list(all_kmers_vector, NULL)
  )
  presence_accumulator_matrix <- matrix(0L,
      nrow = length(all_kmers_vector),
      ncol = bkg_iter,
      dimnames = list(all_kmers_vector, NULL)
  )
  total_bkg_seqs <- 0L

  valid_iterations_count <- 0

  message("Generating average background K-mer profile over ", bkg_iter,
          " iterations (chunk_size=", chunk_size, "):")
  pb <- utils::txtProgressBar(min = 0, max = bkg_iter, style = 3)

  # --- Process in chunks ---
  chunk_starts <- seq(1L, bkg_iter, by = chunk_size)

  for (cs in chunk_starts) {
    chunk_end <- min(cs + chunk_size - 1L, bkg_iter)
    n_this_chunk <- chunk_end - cs + 1L

    # Batched background generation for this chunk
    bkg_result <- generateBkgSetBatched(
      peak_gr = original_peak_gr,
      genome_obj = genome_obj,
      min_seq_length = internal_min_length_for_bkg_seqs,
      bkg_min_dist = bkg_min_dist,
      bkg_max_dist = bkg_max_dist,
      scramble = scramble_bkg,
      n_iter = n_this_chunk,
      extension = extension
    )

    if (length(bkg_result$sequences) > 0) {
      # One oligonucleotideFrequency call for entire chunk
      freq_matrix <- Biostrings::oligonucleotideFrequency(
          bkg_result$sequences, width = K
      )

      # ANR: total counts per iteration
      per_iter_sums <- rowsum(
          freq_matrix,
          group = bkg_result$iter_tags,
          reorder = TRUE
      )

      # ZOOPS: binary presence per iteration
      presence_matrix <- (freq_matrix > 0L) * 1L
      per_iter_presence <- rowsum(
          presence_matrix,
          group = bkg_result$iter_tags,
          reorder = TRUE
      )

      # Map chunk-local iteration indices to global columns
      iter_indices_in_chunk <- as.integer(
          rownames(per_iter_sums)
      )
      global_col_indices <- cs + iter_indices_in_chunk - 1L

      # Store in accumulators
      counts_accumulator_matrix[
          , global_col_indices
      ] <- t(per_iter_sums)
      presence_accumulator_matrix[
          , global_col_indices
      ] <- t(per_iter_presence)

      # Track total background sequences
      total_bkg_seqs <- total_bkg_seqs +
          length(bkg_result$sequences)

      # Count valid iterations
      iter_totals <- rowSums(per_iter_sums)
      valid_iterations_count <- valid_iterations_count +
          sum(iter_totals > 0)
    }

    utils::setTxtProgressBar(pb, chunk_end)
  }
  close(pb)

  # --- Averaging and output ---
  if (valid_iterations_count == 0 && bkg_iter > 0) {
    message(
      "\nNOTE: No valid background sequences yielded counts across any of the ", bkg_iter, " iterations. ",
      "Average background counts will be all zeros."
    )
  } else if (bkg_iter > 0) {
    message(
      "\nBackground profile generated. Averaged over ", valid_iterations_count,
      " iterations that yielded sequences with K-mer counts."
    )
  }

  list(
      MOTIF = all_kmers_vector,
      bkg_total_count = as.integer(
          rowSums(counts_accumulator_matrix)
      ),
      bkg_presence_count = as.integer(
          rowSums(presence_accumulator_matrix)
      ),
      bkg_total_seqs = total_bkg_seqs
  )
}


#' Calculate Background-Corrected K-mer Enrichment
#'
#' @description Computes enrichment scores comparing peak K-mer
#'   counts against background using either ZOOPS (per-sequence
#'   presence) or ANR (total occurrence) models.
#'
#' @param peak_counts_df Data frame from \code{countKmers()}, with
#'   columns MOTIF, COUNT, SEQ_WITH_MOTIF, SEQ_TOTAL.
#' @param bkg_data List from \code{countKmersBkg()}, with elements
#'   MOTIF, bkg_total_count, bkg_presence_count, bkg_total_seqs.
#' @param method Character, "zoops" or "anr". Default: "zoops".
#' @param pseudocount Numeric, added to fractions/rates before
#'   log2 to avoid log(0). Default: 1e-4.
#'
#' @return A data frame with 10 columns: MOTIF, Score, log2FC,
#'   pvalue, padj, target_fraction, bkg_fraction,
#'   target_occurence, bkg_occurence, multiplicity. Score is
#'   min-max normalized enrichment difference (fraction
#'   difference for ZOOPS, rate difference for ANR).
#'
#' @importFrom stats phyper pbinom p.adjust
#' @keywords internal
calEnrichment <- function(peak_counts_df, bkg_data,
                          method = "zoops",
                          pseudocount = 1e-4) {
    method <- match.arg(tolower(method), c("zoops", "anr"))

    n_peak <- peak_counts_df$SEQ_TOTAL[1]
    n_bkg <- bkg_data$bkg_total_seqs

    # ZOOPS fractions (always computed)
    target_fraction <- peak_counts_df$SEQ_WITH_MOTIF / n_peak
    bkg_fraction <- bkg_data$bkg_presence_count / n_bkg

    # ANR rates (always computed)
    target_rate <- peak_counts_df$COUNT / n_peak
    bkg_rate <- bkg_data$bkg_total_count / n_bkg

    # Multiplicity: avg occurrences per containing sequence
    multiplicity <- ifelse(
        peak_counts_df$SEQ_WITH_MOTIF > 0L,
        peak_counts_df$COUNT / peak_counts_df$SEQ_WITH_MOTIF,
        0
    )

    if (method == "zoops") {
        log2FC <- log2(
            (target_fraction + pseudocount) /
            (bkg_fraction + pseudocount)
        )
        pvalue <- stats::phyper(
            q = peak_counts_df$SEQ_WITH_MOTIF - 1L,
            m = peak_counts_df$SEQ_WITH_MOTIF +
                bkg_data$bkg_presence_count,
            n = (n_peak - peak_counts_df$SEQ_WITH_MOTIF) +
                (n_bkg - bkg_data$bkg_presence_count),
            k = n_peak,
            lower.tail = FALSE
        )
        score_raw <- target_fraction - bkg_fraction
    } else {
        log2FC <- log2(
            (target_rate + pseudocount) /
            (bkg_rate + pseudocount)
        )
        p_null <- n_peak / (n_peak + n_bkg)
        pvalue <- stats::pbinom(
            q = peak_counts_df$COUNT - 1L,
            size = peak_counts_df$COUNT +
                bkg_data$bkg_total_count,
            prob = p_null,
            lower.tail = FALSE
        )
        score_raw <- target_rate - bkg_rate
    }

    padj <- stats::p.adjust(pvalue, method = "BH")
    Score <- minmaxNorm(score_raw)

    data.frame(
        MOTIF = peak_counts_df$MOTIF,
        Score = Score,
        log2FC = log2FC,
        pvalue = pvalue,
        padj = padj,
        target_fraction = target_fraction,
        bkg_fraction = bkg_fraction,
        target_occurence = as.integer(peak_counts_df$COUNT),
        bkg_occurence = bkg_rate,
        multiplicity = round(multiplicity, 4),
        stringsAsFactors = FALSE
    )
}

#' Calculate K-mer Motif Enrichment from Genomic Coordinates
#'
#' @description
#' Main workflow function for RBPSpecificity. Processes RBP
#' binding peak data to calculate background-corrected K-mer
#' enrichment scores using either ZOOPS (per-sequence presence)
#' or ANR (total occurrence) statistical models.
#'
#' @details
#' The workflow proceeds as follows:
#' 1. Parses input coordinates into a GRanges object.
#' 2. Loads the specified BSgenome for sequence retrieval.
#' 3. Extracts peak sequences with optional extension/trimming.
#' 4. Counts K-mers (both total and per-sequence presence).
#' 5. Generates background K-mer profiles from shifted regions.
#' 6. Computes enrichment with statistical testing.
#'
#' @param coordinates A data frame or GRanges object with genomic
#'   coordinates. Data frames need chr, start, end columns.
#' @param species_or_build Character, genome build (e.g. "hg38").
#' @param K Integer, K-mer length (e.g. 5).
#' @param extension Numeric vector of length 2:
#'   c(five_prime, three_prime). Positive extends, negative trims.
#'   Default: c(0, 0).
#' @param method Character, enrichment model: "zoops" (default)
#'   for per-sequence presence or "anr" for total occurrences.
#' @param bkg_iter Integer, background iterations. Default: 100.
#' @param bkg_min_dist Integer, min shift distance. Default: 500.
#' @param bkg_max_dist Integer, max shift distance. Default: 1000.
#' @param scramble_bkg Logical, scramble background sequences.
#'   Default: TRUE.
#' @param nucleic_acid_type Character, "DNA" or "RNA".
#'   Default: "DNA".
#'
#' @return A data frame with 10 columns:
#'   \describe{
#'     \item{MOTIF}{K-mer sequence.}
#'     \item{Score}{Min-max normalized log2FC, range [0, 1].}
#'     \item{log2FC}{Log2 fold-change (method-specific).}
#'     \item{pvalue}{Statistical significance (method-specific).}
#'     \item{padj}{Benjamini-Hochberg adjusted p-value.}
#'     \item{target_fraction}{Fraction of peak sequences
#'       containing the motif (ZOOPS).}
#'     \item{bkg_fraction}{Fraction of background sequences
#'       containing the motif (ZOOPS).}
#'     \item{target_occurence}{Total motif occurrences in peaks.}
#'     \item{bkg_occurence}{Background occurrence rate
#'       (per sequence).}
#'     \item{multiplicity}{Average occurrences per containing
#'       sequence.}
#'   }
#' @export
#'
#' @examples
#' \donttest{
#' peaks_file <- system.file("extdata",
#'     "eCLIP_Peaks_HNRNPC.bed",
#'     package = "RBPSpecificity")
#' peaks <- read.table(peaks_file,
#'     header = FALSE, sep = "\t")
#' colnames(peaks) <- c("chr", "start", "end",
#'     "name", "score", "strand")
#' result <- motifEnrichment(peaks, "hg38", K = 5,
#'     method = "zoops", bkg_iter = 5)
#' head(result)
#' }
motifEnrichment <- function(coordinates,
                            species_or_build,
                            K,
                            extension = c(0, 0),
                            method = "zoops",
                            bkg_iter = 100,
                            bkg_min_dist = 500,
                            bkg_max_dist = 1000,
                            scramble_bkg = TRUE,
                            nucleic_acid_type = "DNA") {
    # --- 1. Input Validation ---
    message("--- Phase 1: Validating Inputs ---")
    if (missing(coordinates) ||
        missing(species_or_build) ||
        missing(K)) {
        stop("'coordinates', 'species_or_build', ",
             "and 'K' are required.")
    }
    method <- match.arg(
        tolower(method), c("zoops", "anr")
    )
    if (!is.numeric(extension) || length(extension) != 2) {
        stop("'extension' must be a numeric vector ",
             "of length 2: c(five_prime, three_prime).")
    }
    extension <- as.integer(extension)

    # Load genome
    genome_obj <- selectGenome(species_or_build)
    message("Loaded genome: ", species_or_build)

    # Parse coordinates
    peak_gr <- peakParse(input = coordinates)
    if (length(peak_gr) == 0) {
        stop("No coordinates after parsing.")
    }
    message("Parsed ", length(peak_gr), " coordinates.")

    # --- 2. Peak Sequence Processing ---
    message("\n--- Phase 2: Processing Peak Sequences ---")
    peak_sequences <- getSequence(
        granges_obj = peak_gr,
        genome_obj = genome_obj,
        extension = extension,
        min_length = K
    )
    if (length(peak_sequences) == 0) {
        stop("No sequences retrieved. ",
             "Check coordinates and chromosome names.")
    }
    message("Retrieved ", length(peak_sequences),
            " sequences.")

    peak_kmer_counts <- countKmers(
        sequences = peak_sequences,
        K = K,
        type = nucleic_acid_type
    )
    message("Counted K-mers. ",
            sum(peak_kmer_counts$COUNT > 0),
            " non-zero K-mers.")

    # --- 3. Background Generation ---
    message("\n--- Phase 3: Generating Background ---")
    bkg_kmer_counts <- countKmersBkg(
        original_peak_gr = peak_gr,
        K = K,
        type = nucleic_acid_type,
        genome_obj = genome_obj,
        bkg_min_dist = bkg_min_dist,
        bkg_iter = bkg_iter,
        bkg_max_dist = bkg_max_dist,
        scramble_bkg = scramble_bkg,
        extension = extension
    )
    if (scramble_bkg) {
        message("Background generated (local shift ",
                "+ scrambling).")
    } else {
        message("Background generated (local shift).")
    }

    # --- 4. Enrichment Calculation ---
    message("\n--- Phase 4: Computing Enrichment ---")
    results <- calEnrichment(
        peak_counts_df = peak_kmer_counts,
        bkg_data = bkg_kmer_counts,
        method = method
    )
    message("Enrichment computed using '",
            method, "' method.")

    message("\n--- Workflow Complete ---")
    return(results)
}

#-------------------------------------------------------------------------------
